name: "Dispatch Export"
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: "Godot Version"
        required: true
        default: "4.2.1"
      export_platform:
        description: "Export Platform - web"
        required: true
        default: "web"
      export_folder:
        description: "Export Folder - Repository Path"
        required: true
        default: "."
      export_name:
        description: "Export Name"
        required: true
        default: "bellgame-game"
      release_android:
        description: "Android Release Build"
        required: false
        default: "false"
      itch_io:
        description: "Itch.io Build"
        required: false
        default: "false"

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}
  EXPORT_PLATFORM: ${{ github.event.inputs.export_platform }}
  EXPORT_FOLDER: ${{ github.event.inputs.export_folder }}
  EXPORT_NAME: ${{ github.event.inputs.export_name }}
  RELEASE_ANDROID: ${{ github.event.inputs.release_android }}
  ITCH_IO: ${{ github.event.inputs.itch_io }}

jobs:
  export_web:
    name: Web Export
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.export_platform == 'web' || github.event.inputs.export_platform == 'all' }}
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          cd ${EXPORT_FOLDER}
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Web
          path: ${{ env.EXPORT_FOLDER }}/build/web
      - name: Zip Folder
        run: zip -r itch.zip ${{ env.EXPORT_FOLDER }}/build/web
