name: "Dispatch Export"
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: "Godot Version"
        required: true
        default: "4.2.1"
      export_platform:
        description: "Export Platform - web"
        required: true
        default: "web"
      export_folder:
        description: "Export Folder - Repository Path"
        required: true
        default: "."
      export_name:
        description: "Export Name"
        required: true
        default: "bellgame-game"
      release_android:
        description: "Android Release Build"
        required: false
        default: "false"
      itch_io:
        description: "Itch.io Build"
        required: false
        default: "false"

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}
  EXPORT_PLATFORM: ${{ github.event.inputs.export_platform }}
  EXPORT_FOLDER: ${{ github.event.inputs.export_folder }}
  EXPORT_NAME: ${{ github.event.inputs.export_name }}
  RELEASE_ANDROID: ${{ github.event.inputs.release_android }}
  ITCH_IO: ${{ github.event.inputs.itch_io }}

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Make Working Directory
        run: mkdir /var/app && cd /var/app
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        working-directory: /var/app
        # See https://github.com/godotengine/godot/issues/72360 for description of .godot directories required.
        # Also, create export templates directory where GHA expects it and move templates there
        run: |
          mkdir -v -p .godot/shader_cache build/web /github/home/.local/share/godot/export_templates/
          mv /root/.local/share/godot/templates/4.2.1.stable /github/home/.local/share/godot/export_templates/4.2.1.stable
      - name: Web Build
        run: godot -v --export-debug "Web" --headless ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path:  /var/app/build/web/

